name: release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: build
        run: |
          version=$(git tag --sort=-version:refname | head -n 1)
          module=github.com/pkk82/soft-ver-man
          versionRef=$module/cmd.version
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X $versionRef=$version" -o "soft-ver-man-$version-amd64-linux" $module
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X $versionRef=$version" -o "soft-ver-man-$version-amd64-win" $module
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X $versionRef=$version" -o "soft-ver-man-$version-amd64-darwin" $module
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -ldflags "-X $versionRef=$version" -o "soft-ver-man-$version-arm64-darwin" $module
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "soft-ver-man-*"
